project:
  type: website
  output-dir: docs

website:
  title: "Ghislain Brault-Joubert"
  site-url: https://ghbrj.ca
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - href: cv/cv.qmd
        text: Curriculum Vitae
      - icon: github
        href: https://github.com/braultg

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



