project:
  type: website
  output-dir: docs

website:
  title: "Ghislain Brault-Joubert"
  site-url: https://ghbrj.ca
  favicon: "./images/39a8754-2.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - href: cv/cv.qmd
        text: Curriculum Vitae
      - href: about.qmd
        text: About Me
      - icon: envelope-at
        href: mailto://ghislain@ghbrj.ca
      - icon: linkedin
        href: https://www.linkedin.com/in/ghbrj
      - icon: github
        href: https://github.com/ghbrj
        
lang: en

format:
  html:
    theme: 
      light: litera
      dark: [litera, theme-dark.scss]
    css: styles.css
    toc: true



