project:
  type: website
  output-dir: docs

website:
  title: "Ghislain Brault-Joubert"
  site-url: https://ghbrj.ca
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - CV.qmd
      - icon: github
        href: https://github.com/cynthiahqy

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



