project:
  type: website
  output-dir: docs

website:
  title: "Ghislain Brault-Joubert"
  site-url: https://ghbrj.ca
  navbar:
    right:
      - href: index.qmd
        text: Home      
      - href: cv/cv.qmd
        text: Curriculum Vitae
      - href: about.qmd
        text: About Me
      - icon: github
        href: https://github.com/ghbrj

lang: en

format:
  html:
    theme: 
      light: litera
      dark: [litera, theme-dark.scss]
    css: styles.css
    toc: true



