---
title: "Curriculum Vitae"
format:
  html:
    toc: true
    page-layout: full
    max-width: 1800px  
  pdf:
    author: "Ghislain Brault-Joubert, FCAS"
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
lang: fr
---

::: {.print-only .contact-block}
**Professionnel de l'analytique et Actuaire**<br>
ghislain@ghbrj.ca | Montréal, QC | 514-726-0359
:::

<br> 
À chaque jour, je m'efforce d'influencer une meilleure prise de décision d'affaire grâce aux données. Je collabore avec mes partenaires en entreprise pour identifier, prioriser les enjeux d'affaires et fournir des solutions de données utiles à travers mon travail et celui de mes équipes.

Je désire contribuer et me perfectionner aussi bien en tant que leader analytique qu'analyste de données sénior en m'attaquant à de nouvelles problématiques d'affaires au sein et au-delà du domaine de l'assurance.

Ma philosophie de travail est profondément centrée sur la satisfaction des besoins de mes partenaires d'affaires. Je privilégie des solutions *utiles* et *suffisantes* à de *réelles* problématiques qui aident les entreprises à progresser.

## Expérience 

### Directeur Principal[^1], Analytique de réclamations
*[Co-operators compagnie d'assurances générales](https://www.cooperators.ca/fr-CA/) | Montréal, QC* [*Janvier 2020 --- Aujourd'hui*]{.dateformat}

La promesse faite à ~1M de clients est de les indemniser lorsqu'un événement malheureux survient. La fonction des réclamations paie ~2G$ par an et compte un effectif d'environ 1 600 employés se rapportant à 8-10 vice-présidents adjoints (VPA). Ceci représente une opportunité énorme d'améliorer l'expérience client & employé et de réduire les coûts liés à l'indemnisation. La maturité analytique est relativement faible mais s'améliore.  

La fonction d'analytique au sein du service des réclamations devait croître en raison d'une augmentation rapide et significative de la demande et des attentes des partenaires d'affaires en matière de prise de décision avec des données. Dans cette phase de croissance, il était important de créer et de maintenir un environnement favorable pour assurer le bien-être de notre équipe d'environ 30 professionnels tout en produisant un travail utile et de haute qualité.

**Envers les partenaires en réclamations ayant besoin de solutions analytiques pour améliorer la prise de décision**

- Agi en tant que *leader stratégique* auprès des partenaires pour faciliter l'élicitation des problèmes d'affaires, identifier et prioriser les initiatives en matière de données et superviser l'exécution par les équipes de livraison.  

- Supporté la prise de décision quant à la *gestion des effectifs*, *la gestion de la performance opérationnelle*, *l'amélioration des processus* tels que la segmentation et l'affectation du travail, *l'assurance qualité et le contrôle des risques* et la gestion des *relations et performances avec les fournisseurs*. Avec mes équipes, je résous ces problématiques grâce à l'analyse des données, à la modélisation et à l'aide de visualisations (rapports, tableaux de bord).

***Compétences***: *Planification stratégique et tactique | Résolution de problèmes | Métriques | Analyse de données | Visualisation de données | Apprentissage Machine* 
<br>
***Technologies***: *Outils de collaboration (Teams, Miro) | R | SQL | Jira | Confluence | Git | Guidewire Claim Center*

**Envers les membres de l'équipe d'analytique ayant besoin d'un leadership fort et d'un environnement favorable pour prospérer**

- Agi en tant que *gestionnaire de personnel*, défini les mandats d'équipe, les rôles et responsabilités ainsi que les attentes en matière de performance; Embauché 15+ professionnels de l'analytique; Évalué et récompensé l'atteinte des objectifs; Influencé et mis en oeuvre les changements de structure et de rôles.

- Agi en tant que *chef de pratique*, défini et négocié les modèles d'opération et de service avec le service de réclamation et autres partenaires; Définition des processus de travail associés (admission, priorisation, exécution) et intégration de principes de livraison plus agiles; Définition et mise en œuvre de plans de gestion du changement.

- Agi à titre de *superviseur technique*, fourni du soutien et du coaching sur des questions techniques; Accompagnement des membres de l'équipe dans leur planification de carrière.

***Compétences***: *Gestion de personnel | Gestion de la performance | Amélioration de processus | Négociation | Gestion du changement*

{{< pagebreak >}}
### Directeur Actuariat[^2] & Expert
*[Co-operators compagnie d'assurances générales](https://www.cooperators.ca/fr-CA/) | Montréal, QC* [*Mai 2014 --- Janvier 2020*]{.dateformat}

**Favoriser une croissance rentable des risques entreprise grâce à des initiatives de tarification**

- Dirigé tous les aspects du travail actuariel pour un portefeuille de risques entreprise représentant ~300M$ en prime annuelle. Livré des indications de taux, analyses de segmentation et implémentations de systèmes. Conception et mise en œuvre de nouveaux algorithmes de tarification et d'un outil de sélection des risques.

- Agi à titre de gestionnaire de personnel; supervisé le bien-être professionnel et personnel de 6-8 membres de l'équipe, fixé des objectifs et évalué la performance. Agi à titre de superviseur technique, en fournissant du soutien et du coaching sur des questions techniques; Accompagnement des membres de l'équipe dans leur planification de carrière.

### Consultant en actuariat 
*[Intact corporation financière](https://www.intactfc.com/fr) & AXA Canada | Vancouver, BC* [*Août 2009 --- Avril 2014*]{.dateformat}

Dirigé les mandats de tarification des lignes commerciales pour l'Ouest canadien. Les secteurs d'activité comprenaient les filings en automobile commerciale, les petites et moyennes entreprises, les grands comptes, les assurances spécialisées (E&O, D&O) et la couverture contre les tremblements de terre.

## Éducation 

**M.Sc. Microprogramme - Exploitation de données en intelligence d'affaire** <br> *HEC Montréal | Montréal, QC* [*2018 --- 2019*]{.dateformat}

**B.Sc. Actuariat** <br> *Université Laval | Québec, QC* [*2004 --- 2007*]{.dateformat}

## Titres professionnels

**Fellow, [Casualty Actuarial Society](https://www.casact.org/) (FCAS)** [*Mai 2012 --- Aujourd'hui*]{.dateformat}

**Fellow, [Institut canadien des actuaires](https://www.cia-ica.ca/fr/) (FCIA)** [*Expiré | Novembre 2012 --- Septembre 2022*]{.dateformat}

## Bénévolat et autres expériences

**Administrateur, membre du CA** <br> *[Bibliothèque d'Outils La Remise](https://laremise.ca/) | Montréal, QC* [*Octobre 2017 --- Avril 2019*]{.dateformat}

La Remise est la première bibliothèque d'outils à Montréal. Aidé la coopérative à consolider et à accroître son offre de services aux membres de la communauté locale.

**Programme Relève en gouvernance 2016-2017** <br> *[Institut sur la gouvernance (IGOPP)](https://igopp.org/jaigopp/) | Montréal, QC* [*Novembre 2016 --- Mai 2017*]{.dateformat}

## À propos de moi

**Valeurs** Curiosité | Humilité | Authenticité | Apprentissage et développement

**Forces** Idéation | Adaptabilité | Stratégique | Individualisation | Apprenant *(StrengthFinder 2.0)*

**Langues** Français | Anglais | Allemand (élémentaire) | Espagnol (désire apprendre)

::: {.print-only}
<br><br>
Références disponibles sur demande
:::

<br>

[^1]: Comme directeur principal, j'ai supervisé des directeurs et analystes/scientifiques de données
[^2]: Comme directeur, j'ai supervisé des actuaires juniors et séniors
